### ISSUE TITLE
when i removed a component , i got an error as the following

### ISSUE THREAD

**Issue by yungxiaomcc** [Kitware/paraview-visualizer#12]
## error
ERROR:root:Exception raised
ERROR:root:AttributeError("'NoneType' object has no attribute 'object'")
ERROR:root:Traceback (most recent call last):
  File "/home/yangxiao/projects/paraview-visualizer/.venv/lib/python3.9/site-packages/wslink/backends/aiohttp/__init__.py", line 495, in onMessage
    results = await results
  File "/home/yangxiao/projects/paraview-visualizer/.venv/lib/python3.9/site-packages/trame_server/protocol.py", line 186, in trigger
    result = self.server._triggers[name](*args, **kwargs)
  File "/home/yangxiao/projects/paraview-visualizer/pv_visualizer/html/pipeline.py", line 70, in on_action
    self.server.controller.on_delete(id)
  File "/home/yangxiao/projects/paraview-visualizer/.venv/lib/python3.9/site-packages/trame_server/controller.py", line 277, in __call__
    result = f(*args, **kwargs)
  File "/home/yangxiao/projects/paraview-visualizer/pv_visualizer/app/engine/proxymanager/core.py", line 302, in on_proxy_delete
    pv_source = s_source.object
AttributeError: 'NoneType' object has no attribute 'object'

## click
![image](https://user-images.githubusercontent.com/43135901/237046295-d499b418-d4e6-48bf-9d17-ecfef667ca3f.png)

**Comment by jourdain** [comment]
Thanks for reporting such issue. 

Based on the error it seems that the simput proxy does not exist when triggering the delete. We'll need some time to investigate.

**Comment by yungxiaomcc** [comment]
> Thanks for reporting such issue.
> 
> Based on the error it seems that the simput proxy does not exist when triggering the delete. We'll need some time to investigate.

As I tried to fix this issuse， I found more information .
When I removed a component from pipeline, we expect the component should be removed ,but nothing happened. And one more clicked，the errror occured.
I think there are some states which is not updated synchronously with remove operation.
Can you give me some information to help to investigate it?

**Comment by jourdain** [comment]
Not sure I'm following what you did but I won't have time to investigate anytime soon.
